baseURL = "https://ssudake.com/"
languageCode = "en-us"
title = "Sanket Sudake"
theme = "kiera"
copyright = "Copyright &copy;2018 - Sanket Sudake"

canonifyurl = true
enableEmoji = true
pygmentsCodeFences = true
disqusShortname =  "" #Disqus shortname
googleAnalytics  =  "" #Google Analytics ID

paginate = 5
summaryLength = 30

[author]
    name = "Sanket Sudake"
    github = "ssudake21"
    linkedin = "sanketsudake"
    twitter = "ssudake21"

[params]
    tagline = "Personal thoughts"

