#!/usr/bin/env python3
"""Import the k8s-worksheet book into content/books/k8s-worksheet/.

Reads chapters/ch01.md..ch12.md + appendices.md from the worksheet repo,
adds Hugo front matter, converts ```mermaid fences to the Congo
{{< mermaid >}} shortcode, and regenerates the whole section from scratch.
The generated pages are stamped with the worksheet source commit.

Everything under content/books/k8s-worksheet/ is generated — never hand-edit;
re-run this script after a worksheet release instead:

    python3 scripts/import-k8s-worksheet.py [--worksheet ../k8s-worksheet]
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

BLOG_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = BLOG_ROOT / "content" / "books" / "k8s-worksheet"

# Part structure mirrors the worksheet README; appendices ride at the end.
PARTS = [
    ("Part A — Foundations & control plane internals", [1, 2, 3, 4]),
    ("Part B — Controllers", [5, 6]),
    ("Part C — Standards & extension interfaces", [7, 8, 9]),
    ("Part D — Operating at scale", [10]),
    ("Part E — Judgment at principal scale", [11, 12]),
    ("Reference", [13]),
]

APPENDICES_SUMMARY = (
    "Quick-reference tables, a glossary, the answer-quality rubric, "
    "the principal's lens, and further reading — the book's last-hour revision layer."
)

INDEX_SUMMARY = (
    "A flow-first Kubernetes internals book for senior, staff, and principal "
    "engineers — 30 end-to-end flows, sequence diagrams, failure modes, and "
    "tiered interview questions with model answers."
)


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def toml_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def convert_mermaid(lines: list[str]) -> list[str]:
    """Fence-state-aware conversion: only ```mermaid pairs become shortcodes."""
    out, state = [], None  # state: None | "mermaid" | "other"
    for line in lines:
        stripped = line.strip()
        if state is None and stripped == "```mermaid":
            out.append("{{< mermaid >}}")
            state = "mermaid"
        elif state == "mermaid" and stripped == "```":
            out.append("{{< /mermaid >}}")
            state = None
        elif state is None and stripped.startswith("```"):
            out.append(line)
            state = "other"
        elif state == "other" and stripped == "```":
            out.append(line)
            state = None
        else:
            out.append(line)
    if state is not None:
        sys.exit("error: unbalanced code fence detected during mermaid conversion")
    return out


def first_sentence(text: str) -> str:
    m = re.match(r"(.+?[.!?])(\s|$)", text.strip())
    return m.group(1) if m else text.strip()


def extract_summary(body: str) -> str:
    m = re.search(r"^## Why this chapter\n+(.+?)$", body, re.M)
    return first_sentence(m.group(1)) if m else ""


def parse_chapter(path: Path, number: int) -> dict:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        sys.exit(f"error: {path} does not start with an H1")
    title = lines[0][2:].strip()
    body_lines = lines[1:]
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    if title == "Appendices":
        slug, summary = "appendices", APPENDICES_SUMMARY
    else:
        bare = re.sub(r"^Chapter \d+ — ", "", title)
        slug = slugify(bare)
        summary = extract_summary("\n".join(body_lines))
        if not summary:
            sys.exit(f"error: no 'Why this chapter' summary found in {path}")
    return {
        "number": number,
        "title": title,
        "slug": slug,
        "summary": summary,
        "body": "\n".join(convert_mermaid(body_lines)).rstrip() + "\n",
    }


def front_matter(commit: str, **fields: str) -> str:
    out = ["+++",
           f"# Generated by scripts/import-k8s-worksheet.py from "
           f"sanketsudake/k8s-worksheet@{commit} — do not edit by hand."]
    out += [f"{k} = {v}" for k, v in fields.items()]
    out.append("+++")
    return "\n".join(out)


def build_index(chapters: list[dict], commit: str, date: str) -> str:
    # Congo's prev/next arrows read backwards for weight-ordered sections;
    # the cascade flips them for every chapter at once.
    fm = "\n".join([
        "+++",
        f"# Generated by scripts/import-k8s-worksheet.py from "
        f"sanketsudake/k8s-worksheet@{commit} — do not edit by hand.",
        f"title = {toml_str('Kubernetes Internals Worksheet')}",
        f"date = {date}",
        f"summary = {toml_str(INDEX_SUMMARY)}",
        'images = ["og/k8s-worksheet-book.png"]',
        "groupByYear = false",
        "[cascade]",
        "  invertPagination = true",
        "+++",
    ])
    by_num = {c["number"]: c for c in chapters}
    toc = []
    for part, nums in PARTS:
        toc.append(f"**{part}**\n")
        for n in nums:
            c = by_num[n]
            toc.append(f"- [{c['title']}]({{{{< relref \"{c['slug']}\" >}}}})")
        toc.append("")
    body = f"""{fm}

{chr(10).join(toc)}
"""
    return body


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--worksheet", default=str(BLOG_ROOT.parent / "k8s-worksheet"),
                    help="path to the k8s-worksheet checkout")
    args = ap.parse_args()
    ws = Path(args.worksheet).resolve()
    if not (ws / "chapters").is_dir():
        sys.exit(f"error: {ws} has no chapters/ directory")

    commit = subprocess.check_output(
        ["git", "-C", str(ws), "rev-parse", "--short", "HEAD"], text=True).strip()
    date = subprocess.check_output(
        ["git", "-C", str(ws), "log", "-1", "--format=%cI"], text=True).strip()

    files = [(ws / "chapters" / f"ch{n:02d}.md", n) for n in range(1, 13)]
    files.append((ws / "chapters" / "appendices.md", 13))
    chapters = [parse_chapter(p, n) for p, n in files]

    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    part_of = {n: part for part, nums in PARTS for n in nums}
    written = []
    for c in chapters:
        page_dir = OUT_DIR / c["slug"]
        page_dir.mkdir()
        fm = front_matter(
            commit,
            title=toml_str(c["title"]),
            date=date,
            weight=str(c["number"]),
            summary=toml_str(c["summary"]),
            part=toml_str(part_of[c["number"]]),
            images='["og/k8s-worksheet-book.png"]',
            showTableOfContents="true",
        )
        path = page_dir / "index.md"
        path.write_text(fm + "\n\n" + c["body"], encoding="utf-8")
        written.append(path)

    index = OUT_DIR / "_index.md"
    index.write_text(build_index(chapters, commit, date), encoding="utf-8")
    written.append(index)

    subprocess.check_call(
        [sys.executable, str(BLOG_ROOT / "scripts" / "md-one-sentence-per-line.py"),
         *map(str, written)])
    print(f"imported {len(chapters)} chapters from k8s-worksheet@{commit} into {OUT_DIR}")


if __name__ == "__main__":
    main()
